### ISSUE TITLE
pip install shows errors

### ISSUE THREAD

**Issue by madmanu** [dowjones/dj-dna-streams-python#18]
- Created an empty folder
- Added a `requirements.txt`, having only `git+https://git@github.com/dowjones/dj-dna-streams-python#egg=dj-dna-streams-python`
- Ran `pip3 install -r requirements.txt`
- The logs show :

```shell
coincoin-2:sam manu$ mkdir test
coincoin-2:sam manu$ cat > test/requirements.txt
git+https://git@github.com/dowjones/dj-dna-streams-python#egg=dj-dna-streams-python
^D
coincoin-2:sam manu$ virtualenv venv
Using base prefix '/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/manu/src/sam/venv/bin/python3.7
Also creating executable in /Users/manu/src/sam/venv/bin/python
Installing setuptools, pip, wheel...
done.
coincoin-2:sam manu$ source venv/bin/activate
(venv) coincoin-2:sam manu$ pip3 install -r requirements.txt
Collecting dj-dna-streams-python from git+https://git@github.com/dowjones/dj-dna-streams-python#egg=dj-dna-streams-python (from -r requirements.txt (line 1))
  Cloning https://git@github.com/dowjones/dj-dna-streams-python to /private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-install-u4hkbwc0/dj-dna-streams-python
  Running command git clone -q https://git@github.com/dowjones/dj-dna-streams-python /private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-install-u4hkbwc0/dj-dna-streams-python
  WARNING: Generating metadata for package dj-dna-streams-python produced metadata for project name dj-dna-streaming-python. Fix your #egg=dj-dna-streams-python fragments.
Collecting googleapis-common-protos==1.5.3 (from dj-dna-streaming-python->-r requirements.txt (line 1))
Collecting google-auth==1.0.2 (from dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7f/20/395c536f57f9a7a40500719666c172037eb0ab5d53428cadb80f533051e9/google_auth-1.0.2-py2.py3-none-any.whl
Collecting google-cloud-pubsub==0.38.0 (from dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e5/a0/3360ac59c93af4e65a4fb80e88c59139a9532866680efb1bc792d51909a2/google_cloud_pubsub-0.38.0-py2.py3-none-any.whl
Collecting google-cloud-core==0.28.1 (from dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/0f/41/ae2418b4003a14cf21c1c46d61d1b044bf02cf0f8f91598af572b9216515/google_cloud_core-0.28.1-py2.py3-none-any.whl
Collecting mock==2.0.0 (from dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl
Collecting oauth2client==3.0.0 (from dj-dna-streaming-python->-r requirements.txt (line 1))
Collecting requests==2.20.1 (from dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Collecting protobuf>=3.0.0 (from googleapis-common-protos==1.5.3->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a5/c6/a8b6a74ab1e165f0aaa673a46f5c895af8780976880c98934ae82060356d/protobuf-3.10.0-cp37-cp37m-macosx_10_9_intel.whl
Collecting rsa>=3.1.4 (from google-auth==1.0.2->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from google-auth==1.0.2->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a1/71/8f0d444e3a74e5640a3d5d967c1c6b015da9c655f35b2d308a55d907a517/pyasn1-0.4.7-py2.py3-none-any.whl
Collecting six>=1.9.0 (from google-auth==1.0.2->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth==1.0.2->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.1.1-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from google-auth==1.0.2->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/be/70/e5ea8afd6d08a4b99ebfc77bd1845248d56cfcf43d11f9dc324b9580a35c/pyasn1_modules-0.2.6-py2.py3-none-any.whl
Collecting grpc-google-iam-v1<0.12dev,>=0.11.1 (from google-cloud-pubsub==0.38.0->dj-dna-streaming-python->-r requirements.txt (line 1))
Collecting google-api-core[grpc]<2.0.0dev,>=1.1.0 (from google-cloud-pubsub==0.38.0->dj-dna-streaming-python->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/29/3a/c528ef37f48d6ffba16f0f3c0426456ba21e0dd32be9c61a2ade93e07faa/google_api_core-1.14.3-py2.py3-none-any.whl (68kB)
     |████████████████████████████████| 71kB 4.0MB/s
Collecting pbr>=0.11 (from mock==2.0.0->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/46/a4/d5c83831a3452713e4b4f126149bc4fbda170f7cb16a86a00ce57ce0e9ad/pbr-5.4.3-py2.py3-none-any.whl
Collecting httplib2>=0.9.1 (from oauth2client==3.0.0->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/d2/84/f97b9efdb17c9b73e133bdbf2b4bfd09cd0be655e36e3ee3c4bec9095048/httplib2-0.14.0-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.20.1->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests==2.20.1->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.20.1->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests==2.20.1->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./venv/lib/python3.7/site-packages (from protobuf>=3.0.0->googleapis-common-protos==1.5.3->dj-dna-streaming-python->-r requirements.txt (line 1)) (41.4.0)
Collecting grpcio<2.0.0dev,>=1.0.0 (from grpc-google-iam-v1<0.12dev,>=0.11.1->google-cloud-pubsub==0.38.0->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/75/07/f1d41d10519ca165b0e078949078f20beb57e7e46dc0f1d56b73bb01270a/grpcio-1.24.1-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting pytz (from google-api-core[grpc]<2.0.0dev,>=1.1.0->google-cloud-pubsub==0.38.0->dj-dna-streaming-python->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Building wheels for collected packages: dj-dna-streaming-python, dj-dna-streaming-python
  Building wheel for dj-dna-streaming-python (setup.py) ... done
  Created wheel for dj-dna-streaming-python: filename=dj_dna_streaming_python-1.3.2-cp37-none-any.whl size=12249 sha256=8d2804e4bcdfdbd5338c0049e5e7088191a9174deed81f701f49665f67fe5e5e
  Stored in directory: /private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-ephem-wheel-cache-n7adfsas/wheels/d0/9f/ec/cb1151b4d6a62d42a700bd8dc9147193c673b1e201fad4c832
  Building wheel for dj-dna-streaming-python (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/manu/src/sam/venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-install-u4hkbwc0/dj-dna-streaming-python/setup.py'"'"'; __file__='"'"'/private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-install-u4hkbwc0/dj-dna-streaming-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-wheel-ql9i8gsk --python-tag cp37
       cwd: /private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-install-u4hkbwc0/dj-dna-streaming-python/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Users/manu/src/sam/venv/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-install-u4hkbwc0/dj-dna-streaming-python/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for dj-dna-streaming-python
  Running setup.py clean for dj-dna-streaming-python
  ERROR: Command errored out with exit status 1:
   command: /Users/manu/src/sam/venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-install-u4hkbwc0/dj-dna-streaming-python/setup.py'"'"'; __file__='"'"'/private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-install-u4hkbwc0/dj-dna-streaming-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-install-u4hkbwc0/dj-dna-streaming-python
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Users/manu/src/sam/venv/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/wg/s7fs4xws60d0k0g45lv54n400000gn/T/pip-install-u4hkbwc0/dj-dna-streaming-python/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for dj-dna-streaming-python
Successfully built dj-dna-streaming-python
Failed to build dj-dna-streaming-python
ERROR: google-api-core 1.14.3 has requirement googleapis-common-protos<2.0dev,>=1.6.0, but you'll have googleapis-common-protos 1.5.3 which is incompatible.
Installing collected packages: six, protobuf, googleapis-common-protos, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, grpcio, grpc-google-iam-v1, pytz, certifi, urllib3, chardet, idna, requests, google-api-core, google-cloud-pubsub, google-cloud-core, pbr, mock, httplib2, oauth2client, dj-dna-streaming-python
Successfully installed cachetools-3.1.1 certifi-2019.9.11 chardet-3.0.4 dj-dna-streaming-python-1.3.2 google-api-core-1.14.3 google-auth-1.0.2 google-cloud-core-0.28.1 google-cloud-pubsub-0.38.0 googleapis-common-protos-1.5.3 grpc-google-iam-v1-0.11.4 grpcio-1.24.1 httplib2-0.14.0 idna-2.7 mock-2.0.0 oauth2client-3.0.0 pbr-5.4.3 protobuf-3.10.0 pyasn1-0.4.7 pyasn1-modules-0.2.6 pytz-2019.3 requests-2.20.1 rsa-4.0 six-1.12.0 urllib3-1.24.3
(venv) coincoin-2:sam manu$
```

**Comment by miballe** [comment]
I updated dependencies to newer versions. There's a push request currently in progress to fix this.

**Comment by zakagan** [comment]
this has been merged and resolved
