### ISSUE TITLE
hasn't been updated in months, outdated requirements

### ISSUE THREAD

**Issue by brandolion** [dowjones/dj-dna-streams-python#47]
During installation a host of warnings and errors regarding deprecation are thrown.

Then during execution these errors occur:

```
sudo python3 ./dnaStreaming/demo/show_stream.py
[sudo] password for ubuntu: 
Will log to: /usr/local/lib/python3.10/dist-packages/dnaStreaming-2.2.1-py3.10.egg/dnaStreaming/logs
Traceback (most recent call last):
  File "/home/ubuntu/Documents/dj-dna-streams-python-master/./dnaStreaming/demo/show_stream.py", line 2, in <module>
    from dnaStreaming.listener import Listener
  File "/usr/local/lib/python3.10/dist-packages/dnaStreaming-2.2.1-py3.10.egg/dnaStreaming/listener.py", line 6, in <module>
    from google.api_core.exceptions import GoogleAPICallError, NotFound
  File "/usr/local/lib/python3.10/dist-packages/google_api_core-2.10.1-py3.10.egg/google/api_core/exceptions.py", line 29, in <module>
    from google.rpc import error_details_pb2
ModuleNotFoundError: No module named 'google.rpc'
```

**Comment by cninowize** [comment]
Tested and working as expected
